/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#0b2013',
        'inverse-surface': '#2f312f',
        'inverse-primary': '#ffb956',
        'secondary-container': '#cde6d1',
        tertiary: '#9b4500',
        'tertiary-container': '#f2823b',
        surface: '#faf9f6',
        'on-primary-fixed': '#2a1800',
        'tertiary-fixed': '#ffdbca',
        'on-background': '#1a1c1a',
        'surface-bright': '#faf9f6',
        'on-surface': '#1a1c1a',
        'on-surface-variant': '#524535',
        'primary-fixed-dim': '#ffb956',
        secondary: '#4d6453',
        'tertiary-fixed-dim': '#ffb68e',
        'surface-dim': '#dbdad7',
        error: '#ba1a1a',
        'on-tertiary-container': '#5e2700',
        'surface-container-lowest': '#ffffff',
        'on-primary-container': '#4e3100',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#633f00',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#331200',
        'surface-container-highest': '#e3e2e0',
        'on-tertiary-fixed-variant': '#763300',
        outline: '#847562',
        'primary-container': '#d99116',
        'on-secondary-container': '#516857',
        primary: '#835500',
        'surface-container-low': '#f4f3f1',
        'surface-variant': '#e3e2e0',
        'on-secondary-fixed-variant': '#364c3c',
        'surface-container-high': '#e9e8e5',
        'secondary-fixed': '#d0e9d4',
        'surface-container': '#efeeeb',
        'secondary-fixed-dim': '#b4cdb8',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffddb5',
        'surface-tint': '#835500',
        'inverse-on-surface': '#f2f1ee',
        background: '#faf9f6',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'outline-variant': '#d7c3af',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '20px',
        base: '8px',
        'margin-desktop': '48px',
        'section-gap-desktop': '120px',
        'section-gap-mobile': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-lg': ['"EB Garamond"', 'serif'],
        'display-lg-mobile': ['"EB Garamond"', 'serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'label-md': ['"Work Sans"', 'sans-serif'],
        'body-lg': ['"Work Sans"', 'sans-serif'],
        'body-md': ['"Work Sans"', 'sans-serif'],
        'display-lg': ['"EB Garamond"', 'serif'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
